name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          npm ci
          npm run build
          npm run package

      - name: Lint
        run: |
          npm run lint
          npm run format-check

      - name: Test
        run: npm run test

      - name: Generate code coverage report
        run: |
          npm run test-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
